// This file will be auto-generated by running:
// flutterfire configure --project=shopsmart-0001
//
// For now, this is a placeholder. Run the command above after:
// 1. Installing Flutter SDK
// 2. Installing Firebase CLI: npm install -g firebase-tools
// 3. Installing FlutterFire CLI: dart pub global activate flutterfire_cli
// 4. Running: flutterfire configure --project=shopsmart-0001

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  // REPLACE THESE with your actual values from flutterfire configure
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA8UxrzFVh7LF4d5ZG8PNrEx8f3VdpwX0',
    appId: '1:539744292760:web:4c8dc1c7993c9cbb63e5ed',
    messagingSenderId: '539744292760',
    projectId: 'shopsmart-0001',
    storageBucket: 'shopsmart-0001.firebasestorage.app',
  );
}
